### ISSUE TITLE
Doesn't work on node v0.8.x

### ISSUE THREAD

**Issue by TooTallNate** [christkv/node-git#18]
It seems this module still depends on the old `compress` module, which should be dropped in favor of the native `zlib` module.

```
☮ ~ (master) ⚡ npm install git
npm http GET https://registry.npmjs.org/git
npm http 304 https://registry.npmjs.org/git
npm http GET https://registry.npmjs.org/compress
npm http 304 https://registry.npmjs.org/compress

> compress@0.1.9 install /Users/nrajlich/node_modules/git/node_modules/compress
> node-waf clean ; node-waf configure build

Nothing to clean (project not configured)
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for library z                   : yes 
'configure' finished successfully (0.095s)
Waf: Entering directory `/Users/nrajlich/node_modules/git/node_modules/compress/build'
[1/2] cxx: compress.cc -> build/Release/compress_1.o
../compress.cc:2:25: error: node_events.h: No such file or directory
../compress.cc:14: error: expected class-name before ‘{’ token
../compress.cc: In static member function ‘static void Gzip::Initialize(v8::Handle<v8::Object>)’:
../compress.cc:23: error: ‘EventEmitter’ has not been declared
../compress.cc: In static member function ‘static v8::Handle<v8::Value> Gzip::New(const v8::Arguments&)’:
../compress.cc:122: error: ‘class Gzip’ has no member named ‘Wrap’
../compress.cc: In constructor ‘Gzip::Gzip()’:
../compress.cc:198: error: class ‘Gzip’ does not have any field named ‘EventEmitter’
../compress.cc: At global scope:
../compress.cc:212: error: expected class-name before ‘{’ token
../compress.cc: In static member function ‘static void Gunzip::Initialize(v8::Handle<v8::Object>)’:
../compress.cc:221: error: ‘EventEmitter’ has not been declared
../compress.cc: In static member function ‘static v8::Handle<v8::Value> Gunzip::New(const v8::Arguments&)’:
../compress.cc:302: error: ‘class Gunzip’ has no member named ‘Wrap’
../compress.cc: In constructor ‘Gunzip::Gunzip()’:
../compress.cc:357: error: class ‘Gunzip’ does not have any field named ‘EventEmitter’
Waf: Leaving directory `/Users/nrajlich/node_modules/git/node_modules/compress/build'
Build failed:  -> task failed (err #1): 
    {task: cxx compress.cc -> compress_1.o}
npm ERR! compress@0.1.9 install: `node-waf clean ; node-waf configure build`
npm ERR! `sh "-c" "node-waf clean ; node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the compress@0.1.9 install script.
npm ERR! This is most likely a problem with the compress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean ; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls compress
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "git"
npm ERR! cwd /Users/nrajlich
npm ERR! node -v v0.8.2
npm ERR! npm -v 1.1.33
npm ERR! code ELIFECYCLE
npm ERR! message compress@0.1.9 install: `node-waf clean ; node-waf configure build`
npm ERR! message `sh "-c" "node-waf clean ; node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nrajlich/npm-debug.log
npm ERR! not ok code 0
```
